import { Roboto_Mono as FontSans } from "next/font/google";
import { Footer, Header } from "@/components/nav";
import { Provider } from "@/components/provider";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import "./globals.css";


const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "DACS Favor Swapper",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body 
        className={cn(
          "min-h-screen bg-background font-sans antialiased flex flex-col",
          fontSans.variable
        )}
      >
        <Provider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <main className="flex flex-col flex-1 h-full">
            {children}
          </main>
          <Footer />
          <Toaster richColors/>
        </Provider>
      </body>
    </html>
  );
}
